variables:
- group: shared

trigger:
  branches:
    include: 
    - develop
    - master
  paths:
    include: 
     - /src/*

resources:
  repositories:
  - repository: devops
    type: git
    name: pub/devops
    ref: refs/heads/master

stages:
- template: azure-pipelines/Config1.SettingsIni/main.yml@devops